api_platform:
    title: Moto API
    version: 1.0.0
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    enable_swagger_ui: true
    enable_re_doc: true
    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']
    docs_formats:
        jsonld: ['application/ld+json']
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization']
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true
    serializer:
        hydra_prefix: true