version: '3.8'

services:

  php:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:8.2-fpm
    container_name: php
    volumes:
      - .:/var/www/html
    networks:
      - backend
    environment:
      DATABASE_URL: "mysql://moto:api@mysql:3306/motos_db"
      DATABASE_URL_TEST: "mysql://moto:api@mysql:3306/motos_db_test"
    command: >
      bash -c "chmod -R 777 public/bundles && php-fpm"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: motos_db
      MYSQL_USER: moto
      MYSQL_PASSWORD: api
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql:/docker-entrypoint-initdb.d
    networks:
      - backend

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - 8081:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - .:/var/www/html
    depends_on:
      - php
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  db_data: